version: "3.9"

services:
  db:
    image: postgres:16-bullseye
    env_file:
      - .env
    volumes:
      - pg-vol:/var/lib/postgresql/data
    networks:
      - test-network
  api:
    build: .
    env_file:
      - .env
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - "8000:8000"
    links:
      - db:db
    networks:
      - test-network
  redis:
    image: library/redis:5.0-alpine
    restart: unless-stopped
    networks:
      - test-network

networks:
  test-network:
    driver: bridge

volumes:
  pg-vol:
