# Generated by Django 5.0 on 2024-02-08 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_blog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
    ]
